"""add email verification to users

Revision ID: 642419e6d19f
Revises: 1332cae5006d
Create Date: 2026-03-12 12:27:30.597961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642419e6d19f'
down_revision = '1332cae5006d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
