"""friendship table update and chatroom table delete

Revision ID: fd8efd015c01
Revises: 0b8552b77155
Create Date: 2026-03-03 13:39:13.765617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8efd015c01'
down_revision = '0b8552b77155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requestee_id', sa.Integer(), nullable=True),
    sa.Column('acceptee_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('requestee_id != acceptee_id', name='no_self_friendship'),
    sa.ForeignKeyConstraint(['acceptee_id'], ['users.id'], name=op.f('fk_friendships_acceptee_id_users')),
    sa.ForeignKeyConstraint(['requestee_id'], ['users.id'], name=op.f('fk_friendships_requestee_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requestee_id', 'acceptee_id', name='unique_friendship')
    )
    op.drop_table('friends')
    op.drop_table('chatrooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatrooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], name='fk_chatrooms_friend_id_friends'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chatrooms_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friendships')
    # ### end Alembic commands ###
