"""email verification removed

Revision ID: fe215434291b
Revises: 642419e6d19f
Create Date: 2026-03-27 19:49:21.135765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe215434291b'
down_revision = '642419e6d19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_verification_token', type_='unique')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint('uq_users_verification_token', ['verification_token'])

    # ### end Alembic commands ###
